server:
  servlet:
    context-path: /api/sl

spring: 
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  kafka: 
    produce-enable: true
    consume-enable: true

service: 
  # 文件上传每小时频率限制次数
  upload-limit: 30
  # websocket校验跨域origin,正确配置此值，否则会导致websocket握手失败
  wsOrigin: https://www.ichargehub.com
