server:
  port: 10212

spring:
  application:
    name: icharge-auth
  cloud:
    nacos:
      server-addr: "[2607:fcd0:100:000e:0000:0000:aacd:74ba]:38838"
      config:
        server-addr: "[2607:fcd0:100:000e:0000:0000:aacd:74ba]:38838"
        namespace: 059a88cd-8bda-46ce-9e69-dfc3c541014a
        group: DEFAULT_GROUP
        file-extension: yaml
        username: test
        password: yan51121
  #        import-check:
#          enabled: false
      discovery:
        group: DEFAULT_GROUP
        username: test
        password: yan51121
        namespace: 059a88cd-8bda-46ce-9e69-dfc3c541014a
      username: test
      password: yan51121
  config:
    import:
      - optional:nacos:icharge-auth.yaml?refreshEnabled=true