server:
  port: 10211

spring:
  application:
    name: icharge-web


oss:
  # oss类型，目前支持：阿里云(0) 七牛云(1) 又拍云(2) 本地存储(3) 通用S3协议 (4)
  ossType: 1
  access-key: eNmxT0s01OOlBmM7gwSufviBOs0ndxW7JbPU-odP
  secret-key: ER7CH9EfPNVFIPn2N7QS3kVpvToDuN9swyZ0oxDR
  endpoint:
